spring:
  #静态资源处理
  resources:
    #启用默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存响应时间，单位秒
        max-age: 3600
    chain:
      #资源链中启用缓存，默认启用
      cache: true
      #启用资源链，默认禁用
      enabled: true
      #启用压缩资源(gzip,brotli)解析,默认禁用
      compressed: true
      #启用H5应用缓存，默认禁用
      html-application-cache: true
    #静态资源位置
    static-locations: classpath:/static/

  # thymeleaf \u914D\u7F6E
  thymeleaf:
    # \u5173\u95ED\u7F13\u5B58
    cache: false
  # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 192.168.72.148
    #服务器端口
    port: 6379
    #数据库
    database: 0
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  #RabbitMQ
  rabbitmq:
    #服务器地址
    host: 192.168.72.139
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间 默认1000ms
        initial-interval: 1000
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000
        #重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s
        multiplier: 1.0

# mybatis-plus\u914D\u7F6E
mybatis-plus:
  # \u914D\u7F6EMapper.xml\u7684\u6620\u5C04\u6587\u4EF6
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # \u914D\u7F6EMybatis\u6570\u636E\u8FD4\u56DE\u7C7B\u578B\u522B\u540D\uFF08\u9ED8\u8BA4\u522B\u540D\u662F\u7C7B\u540D\uFF09
  type-aliases-package: com.wang.seckill.pojo

# Mybatis SQL\u6253\u5370\uFF08\u65B9\u6CD5\u63A5\u53E3\u6240\u5728\u7684\u5305\uFF0C\u4E0D\u662FMapper.xml\u6240\u5728\u7684\u5305\uFF09
logging:
  level:
    com.wang.seckill.mapper: debug